[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "7af2d3e8bfe279b374beb3de0a93f237457eac64"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "885eed8d65e9b10165d1e9e3a742d04d4233c9484a5c513bb71199b7a55b9383"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.arm-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "f9366f411ffe913d175f195df59a625fc294b02f"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "f9fe19869a669a02c45b2ea1659b1647483ee6383ec8c77813100bf9d4154b11"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.aarch64-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "49e50bedb0be5072478c6486fa90d3faeecacd18"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "552cd0d8f49973903c689699719de580756ad8bf07f1e44e6b0f64cad6cf330a"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.i686-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "a6eb5180b52ea7afde5e570509d5891db353b90f"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "bd5b8299e02d4fa8fa604bb7e6243716930065e8f17ccdbc3ace6bc74e2946a9"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.i686-linux-gnu.tar.gz"
[[Keyutils]]
arch = "powerpc64le"
git-tree-sha1 = "8786b5118eb9aa32c00af462a16b52c9110d7eb0"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "37ee363f1bab6e1e03e1ec36f76af84466efd30806752e7128c82f93c6f19d1f"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "bb341bec3e5bd7e1013a6881ec401d238d6f3035"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "61511f2418c769b7a9100fd43869568dd84db2eb4ed0aa247bd25094d35390fa"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.arm-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "270f093fc0905ad3f06aa74279afe30a1f4a9b82"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "a88fe957ebd19e674b476b551dcf74bf8586613149d3013c90d7bc52342c023d"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.aarch64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "f25884fdf42fb6e34f903a6d8510ec1f0eb36269"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "d69ff41c5a9160cf8507d4455519d957fbe490aa57fa4cf64df570c15532dda5"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.x86_64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "f99dac4c7cd7ada73ed3145854dff7049bed7010"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "299ca410e0d8dbee0e22f4968c82cdb9ee771572ce370cd425021803df8b4916"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+1/Keyutils.v1.6.1.x86_64-linux-musl.tar.gz"
